_target_: src.networks.SwinNet.SwinNet
input_channel: 12
hidden_dim: 64
downscaling_factors: [4, 2, 1, 1]
layers: [2, 2, 2, 2]
heads: [4, 4, 4, 4]
head_dim: 64
window_size: 8
input_resolution: [256, 256]
lstm_layers: 2
num_classes: 5
output_frames: 1
